import {
  Zap,
  Flame,
  Layers,
  Armchair,
  BedDouble,
  Music,
  Table,
  HardHat,
  Monitor,
  Dumbbell,
  TreePine,
  Thermometer,
  CircleDot,
  Tv,
  type LucideIcon,
} from "lucide-react";

export interface TabItem {
  label: string;
  icon: LucideIcon;
  title: string;
  text: string;
  items: string[];
  extraItems?: string[];
}

export const TAB_DATA: TabItem[] = [
  {
    label: "Appliances",
    icon: Zap,
    title: "Appliance Removal",
    text: "From small kitchen gadgets to full-size washers and dryers — we lift, load, and send everything off for eco-friendly disposal. We make sure your appliances are properly recycled, donated, or responsibly disposed of.",
    items: [
      "Air Conditioner",
      "Freezers",
      "Microwaves",
      "Dishwashers",
      "Stoves",
      "Ovens",
      "Cooktops",
      "Trash Compactors",
      "Wine Coolers",
      "Washer",
      "Dryer",
      "Dehumidifier",
      "Refrigerator",
      "Water Heater",
      "Furnace",
      "Toaster Oven",
      "Blender",
      "Coffee Maker",
      "Fan",
      "Space Heater",
      "Vacuums",
      "Sewing Machine",
      "Lamp",
      "Wood Burning Stove",
      "Outdoor Grill",
      "Outdoor Fireplace/Pit",
    ],
  },
  {
    label: "BBQ Grills",
    icon: Flame,
    title: "BBQ Grill Removal",
    text: "Outdoor grills, smokers, table-top grills — we donate what we can and responsibly dispose of the rest.",
    items: [
      "Gas Grills",
      "Propane Grills",
      "Charcoal Grills",
      "Rotisserie Grills",
      "Smokers",
      "Commercial Grills",
      "Flat Top Grills",
      "Hibachi Grills",
      "Outdoor Built-In Grills",
      "Pizza Ovens",
      "Table Top Grills",
      "Camping Grills",
    ],
  },
  {
    label: "Carpets & Rugs",
    icon: Layers,
    title: "Carpet & Rug Removal",
    text: "Residential or commercial carpeting, indoor/outdoor rugs and padding — we remove them all, no mess left behind.",
    items: [
      "Carpeting",
      "Carpet Padding",
      "Carpet Tiles",
      "Carpet Runners",
      "Throw Rugs",
      "Area Rugs",
      "Ruggables",
      "Carpet Remnants",
      "Commercial Carpeting",
      "Industrial Carpeting",
      "Outdoor Carpeting",
      "Indoor/Outdoor Carpeting",
    ],
  },
  {
    label: "Furniture",
    icon: Armchair,
    title: "Furniture Removal",
    text: "Heavy, bulky, awkward — we expertly navigate corners and stairs to remove any furniture from any room. We donate, recycle, or responsibly dispose. We even do curbside pickups and offer same-day service.",
    items: [
      "Couch",
      "Loveseat",
      "Sofa",
      "Chairs",
      "Recliner",
      "Rocker",
      "End Table",
      "Coffee Table",
      "Dining Room Table",
      "Kitchen Table",
      "Bench",
      "Desk",
      "Hutch",
      "Bookcase",
      "Filing Cabinet",
      "Dresser",
      "Nightstand",
      "Mattress",
      "Box Spring",
      "Futon",
      "Armoire",
      "TV Stand",
      "Entertainment Center",
      "Sectional Sofa",
      "Daybed",
      "Patio Furniture",
      "Sleeper Sofa",
      "Ottoman",
      "Sofa Table",
      "Card Table",
      "Stool",
      "Cabinet",
      "Cupboard",
      "Wardrobe",
      "Chest",
      "Headboards/Footboard",
      "Cot",
      "China Cabinet",
      "Roll-a-way Bed",
    ],
    extraItems: [
      "Commercial Filing Cabinets",
      "Cabinetry",
      "Credenza",
      "Office Desk",
      "Conference Table",
      "Wall Partitions",
      "Artwork",
      "Office Furniture",
      "Breakroom Furniture",
      "Fixtures",
      "Reception Furniture",
      "Shelving",
      "Cubicles",
      "Desk Chairs",
    ],
  },
  {
    label: "Mattresses",
    icon: BedDouble,
    title: "Mattress Removal & Recycling",
    text: "We specialize in removing all unwanted mattresses, bed frames, and bedroom furniture — recycled the right way.",
    items: [
      "Mattresses",
      "Foam Mattresses",
      "Latex Mattresses",
      "Air Mattresses",
      "Water Beds",
      "Bunkbed Mattresses",
      "Hospital Bed Mattresses",
      "Futon Mattresses",
      "Box Springs",
      "Canopy Bed Mattresses",
    ],
  },
  {
    label: "Pianos",
    icon: Music,
    title: "Piano & Organ Removal",
    text: "From baby grands to digital keyboards — we take them all and whenever possible find a second home for them through donation.",
    items: [
      "Upright Pianos",
      "Baby Grand Pianos",
      "Console Pianos",
      "Spinet Pianos",
      "Electric Organs",
      "Keyboards",
    ],
  },
  {
    label: "Pool Tables",
    icon: Table,
    title: "Pool Table Removal",
    text: "Heavy slate, bulky frames, and awkward disassembly — we handle it all. Your old pool table will be properly recycled or donated whenever possible.",
    items: [
      "Upright Pool Tables",
      "Bar Box Pool Tables",
      "Tournament Pool Tables",
      "Pool Table Slate",
      "Pool Table Felt",
      "Pool Table Rails",
      "Pool Table Pockets",
      "Pool Table Legs",
      "Pool Table Lights",
      "Pool Table Covers",
      "Cue Racks",
      "Pool Cues",
    ],
  },
  {
    label: "Construction",
    icon: HardHat,
    title: "Construction Debris Removal",
    text: "We clear your job site fast. Drywall, tile, wood, concrete — everything that's left after the build.",
    items: [
      "Drywall / Sheetrock",
      "Windows",
      "Doors",
      "Stone / Gravel",
      "Concrete",
      "Fencing",
      "Plywood / Wood",
      "Wood Flooring",
      "Tile",
      "Laminate",
      "Bathtubs",
      "Vanities",
      "Brick",
      "Plaster",
      "Carpeting",
      "Appliances",
    ],
  },
  {
    label: "Electronics",
    icon: Monitor,
    title: "Electronics Removal",
    text: "Earth-friendly e-waste recycling and disposal. From phones and laptops to printers and gaming systems — we haul it all.",
    items: [
      "Flat Screen TVs",
      "Tube TVs",
      "Computers",
      "Laptops",
      "Tablets",
      "Monitors",
      "Printers",
      "Scanners",
      "Projectors",
      "Cameras",
      "Stereos",
      "Speakers",
      "Gaming Systems",
      "Xbox",
      "Nintendo",
      "Routers",
      "Modems",
      "Copy Machines",
      "Fax Machines",
      "Hard Drives",
      "Phones",
      "Smart TVs",
      "Plasma TVs",
      "LED/OLED TVs",
    ],
  },
  {
    label: "Exercise Equipment",
    icon: Dumbbell,
    title: "Exercise Equipment Removal",
    text: "From small cardio steppers to full home gym setups — we make sure your gear is properly recycled or donated.",
    items: [
      "Rowing Machines",
      "Treadmills",
      "Stair Steppers",
      "Weight Benches",
      "Weights",
      "Ellipticals",
      "Exercise Bikes",
      "Punching Bags",
      "Pilates Machines",
      "Home Gym Gear",
      "Exercise Balls",
      "Mats",
      "Ski Ergs",
      "Weight Bars",
      "Cardio Equipment",
    ],
  },
  {
    label: "Playsets & Trampolines",
    icon: TreePine,
    title: "Playset & Trampoline Removal",
    text: "Reclaim your yard. We safely dismantle and remove old swing sets, trampolines, playhouses and jungle gyms — no matter how weathered or rusted.",
    items: [
      "Playsets",
      "Swing Sets",
      "Trampolines",
      "Playhouses",
      "Tree Houses",
      "Wooden Playsets",
      "Metal Swing Sets",
      "Jungle Gyms",
      "Slides",
      "Merry Go Rounds",
      "Commercial Playgrounds",
      "Climbing Walls",
    ],
  },
  {
    label: "Refrigerators",
    icon: Thermometer,
    title: "Refrigerator & Freezer Removal",
    text: "From dorm fridges to commercial walk-ins — we lift, load, and send them off for earth-friendly disposal. Properly recycled, donated, or responsibly disposed.",
    items: [
      "Refrigerators",
      "Iceboxes",
      "Freezers",
      "Commercial Refrigeration Units",
      "Commercial Freezers",
      "Side by Side Refrigerators",
      "Wine Coolers",
      "Beer Fridges",
      "Ice Machines",
      "Deep Freezers",
      "Dorm Fridges",
    ],
  },
  {
    label: "Tires & Wheels",
    icon: CircleDot,
    title: "Tire, Rim & Wheel Removal",
    text: "From bicycles to semi-trucks — we haul, load, and recycle all tires and wheels. Don't risk damage to your vehicle or spend money on a dumpster rental.",
    items: [
      "Bicycle Tires",
      "Auto Tires",
      "Truck Tires",
      "Motorcycle Tires",
      "ATV Tires",
      "4-Wheeler Tires",
      "Van Tires",
      "Wheels",
      "Rims",
      "Lawnmower Tires",
    ],
  },
  {
    label: "Televisions",
    icon: Tv,
    title: "Television Removal & Recycling",
    text: "Television disposal can be complicated — the components within can be hazardous. We maneuver around tight corners and make sure to dispose of your TV properly. Same-day and next-day service available.",
    items: [
      "Flat Screen TVs",
      "Tube TVs",
      "3D TVs",
      "Smart TVs",
      "Plasma TVs",
      "Projection TVs",
      "Console TVs",
      "HD & UHD TVs",
      "LED & OLED TVs",
      "Computers",
      "Laptops",
      "Tablets",
      "Monitors",
      "Printers",
      "Scanners",
      "Projectors",
    ],
  },
];
